server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /calendar/;
    }

    location /calendar/ {
        try_files $uri $uri/ /calendar/index.html;
    }
}
